/**
* @file RenderGraph.h
* @author Andrew Fagan
* @date 7/7/2025
*/

#pragma once

#include "Core/Containers/DirectedGraph.h"
#include "Renderer/Common/SceneRendererTypes.h"
#include "Renderer/RHI/Resources/Texture.h"
#include "Renderer/RHI/Resources/DescriptorSet.h"
#include "Renderer/RHI/Resources/CommandBuffer.h"
#include "RenderGraphPass.h"

#include <vector>


namespace Astral {

    using PassIndex = uint8;
    static constexpr PassIndex NullRenderPassIndex = -1;

    /**
     * @brief Manages the creation and execution of a render graph consisting of multiple render passes.
     *        Provides methods to build, execute, and resize render graph resources.
     */
    class RenderGraph
    {
    public:

        // TODO: Add support for adding buffers as a resource to a render pass
        // TODO: Add support for texture aliasing

        /**
         * @brief Marks the beginning of calls to collect render passes and other information to build the render graph
         * @param maxFramesInFlight The max frames in flight
         * @param debugName A name to assign to the graph that is used to label graph operators with
         * @post  @ref EndBuildingRenderGraph is called after all passes and output images are added to create the render graph
         * @warning This invalidates any previous render graph built in this instance
         */
        void BeginBuildingRenderGraph(uint32 maxFramesInFlight, const std::string_view& debugName = "Untitled Render Graph");

        /**
         * @brief Adds a render pass to the render graph
         * @param pass The render pass to add to the graph
         * @pre   @ref BeginBuildingRenderGraph is called first
         */
        void AddPass(const RenderGraphPass& pass);

        /**
         * @brief Adds an output render pass to the render graph
         * @param pass The render pass to add to the graph
         * @pre   @ref BeginBuildingRenderGraph is called first
         */
        void AddOutputPass(const RenderGraphPass& pass);

        /**
         * @brief Sets the output of the render graph to a specific attachment in a render pass
         * @param pass The render pass that the output attachment is in
         * @param attachmentName The name of the attachment that should use the output textures
         * @param outputAttachmentDimensions The dimensions of the output attachment
         */
        void SetOutputAttachment(const RenderGraphPass& pass, std::string_view attachmentName, UVec2 outputAttachmentDimensions);

        /**
         * @brief Ends the building of the render graph and compiles the render graph
         * @pre   @ref BeginBuildingRenderGraph is called first
         */
        void EndBuildingRenderGraph();

        /**
         * @brief Starts running the render passes in the graph
         * @param sharedFrameContext The command buffer to record render commands generated by the render graph passes into
         * @param swapchainImageIndex The swapchain image index acquired this frame
         * @param outputAttachmentTexture
         * @note  Barriers and layout transitions happen automatically between render passes if needed
         * @pre   @ref EndBuildingRenderGraph is called first to create render graph and its resources
         */
        const std::vector<CommandBufferHandle>& Execute(SharedFrameContext& sharedFrameContext,
                                                        uint32 swapchainImageIndex,
                                                        const TextureHandle& outputAttachmentTexture);

        /**
         * @brief Recreates the render graph resources (textures, framebuffers, and descriptor sets)
         * @param outputAttachmentDimensions The new dimensions of the output attachment
         * @pre   @ref EndBuildingRenderGraph is called first to create render graph and its resources
         */
        void ResizeResources(UVec2 outputAttachmentDimensions);

        /**
         * @brief Clears any held resources from previous render graphs
         * @pre   @ref EndBuildingRenderGraph is called first to create render graph and its resources
         */
        void ClearResourceHold();

    private:

        /**
         * @brief Contains the resources for a render pass to be executed
         */
        struct RenderPassResources
        {
            DescriptorSetHandle ReadAttachmentDescriptorSet;
            std::vector<AttachmentResource> AttachmentResources;
            std::vector<TextureHandle> AttachmentTextures;
        };

        /**
         * @brief Builds the directed acyclic render graph
         * @details The edges in the graph represent a dependency between render passes
         */
        void BuildRenderGraph();

        /**
         * @brief Figures out the execution order of all the render passes
         * @details Does a topological sort to figure out the render passes that don't have a dependency to run first
         */
        void SolveRenderPassExecutionOrder();

        /**
         * @brief Manages the layout transitions of attachments between render passes
         */
        void CompileRenderPassBarriers();

        /**
         * @brief Manages the layout transitions of read attachments during execution
         */
        void TransitionReadAttachmentLayouts(CommandBufferHandle commandBuffer, const RenderGraphPass& pass, uint32 swapchainImageIndex);

        /**
         * @brief Manages the synchronization and layout transitions of attachments before execution of a render graph pass
         */
        void TransitionAttachmentsToOptimalLayouts(CommandBufferHandle commandBuffer, const RenderGraphPass& pass, uint32 swapchainImageIndex);

        /**
         * @brief Updates the output attachment resource references with the current frame's output attachment texture
         */
        void UpdateOutputAttachmentResourceReferences(const TextureHandle& outputAttachmentTexture, uint32 swapchainImageIndex);

        /**
         * @brief Creates the RHI render pass object for each render pass
         */
        void BuildRenderPassObjects();

        /**
         * @brief Creates the RHI render pass object for each render pass
         */
        void BuildRenderPassResources();

        /**
         * @brief Gets the render pass index from a @ref RenderGraphPass instance
         */
        PassIndex GetRenderPassIndex(const RenderGraphPass& pass);

        /**
         * @brief Adds the current render graph resources to the render graph resources hold
         */
        void AddRenderGraphResourcesToHold();

        /**
         * @brief Updates the render graph resources hold by removing resources from the hold when necessary
         */
        void UpdateRenderGraphResourcesHold();


        /**
         * @brief Contains all the resources for each render pass in the render graph
         */
        using RenderGraphResources = std::vector<std::vector<RenderPassResources>>;


        // Contains all the render graph passes that were added to the graph
        std::vector<RenderGraphPass> m_Passes;


        // The graph used to figure out dependencies between render graph and to cull non-contributing render passes
        DirectedGraph<PassIndex> m_RenderGraph;
        std::vector<DirectedGraph<PassIndex>::Vertex> m_RenderPassNodes;


        // Contains the order of render passes to execute in such that dependencies are ran first
        std::vector<PassIndex> m_ExecutionOrder;
        // Contains the RHI objects needed to execute all render passes that are in the execution order
        std::vector<RenderPassHandle> m_RenderPasses;
        RenderGraphResources m_RenderPassResources;
        uint32 m_MaxFramesInFlight{0};

        std::vector<std::vector<CommandBufferHandle>> m_RenderPassCommandBuffers;

        // Vectors to hold render graph resources after a resize, so they don't get deleted while being used on the gpu
        std::vector<RenderGraphResources> m_RenderPassResourcesHold;
        std::vector<std::vector<RenderPassHandle>> m_RenderPassesHold;
        std::vector<uint32> m_FramesTillClear;


        // The render pass and attachment where the output textures should be used instead of creating new textures
        PassIndex m_OutputRenderPassIndex{0};
        std::string_view m_OutputAttachmentName;
        PassIndex m_OutputAttachmentPass{0};
        UVec2 m_OutputAttachmentDimensions{0};


        // Debug name for the render graph
        std::string_view m_DebugName;
        uint64 m_ResourceBatchNumber = 0;
    };

}


// TODO: Refactor impl for clarity
// TODO: Add fallback if render graph compilation fails during a release build