/**
* @file ImageLayouts.h
* @author Andrew Fagan
* @date 6/11/2025
*/


#pragma once

#include "Core/FixedIntegerTypes.h"

namespace Astral {

    enum class ImageLayout : uint8
    {
        UNDEFINED,
        GENERAL,
        COLOR_ATTACHMENT_OPTIMAL,
        DEPTH_STENCIL_ATTACHMENT_OPTIMAL,
        DEPTH_STENCIL_READ_ONLY_OPTIMAL,
        SHADER_READ_ONLY_OPTIMAL,
        TRANSFER_SRC_OPTIMAL,
        TRANSFER_DST_OPTIMAL,
        PREINITIALIZED,
        DEPTH_READ_ONLY_STENCIL_ATTACHMENT_OPTIMAL,
        DEPTH_ATTACHMENT_STENCIL_READ_ONLY_OPTIMAL,
        DEPTH_ATTACHMENT_OPTIMAL,
        DEPTH_READ_ONLY_OPTIMAL,
        STENCIL_ATTACHMENT_OPTIMAL,
        STENCIL_READ_ONLY_OPTIMAL,
        READ_ONLY_OPTIMAL,
        ATTACHMENT_OPTIMAL,
        PRESENT_SRC_KHR,
        VIDEO_DECODE_DST_KHR,
        VIDEO_DECODE_SRC_KHR,
        VIDEO_DECODE_DPB_KHR,
        SHARED_PRESENT_KHR,
        FRAGMENT_DENSITY_MAP_OPTIMAL_EXT,
        FRAGMENT_SHADING_RATE_ATTACHMENT_OPTIMAL_KHR,
        RENDERING_LOCAL_READ_KHR,
        VIDEO_ENCODE_DST_KHR,
        VIDEO_ENCODE_SRC_KHR,
        VIDEO_ENCODE_DPB_KHR,
        ATTACHMENT_FEEDBACK_LOOP_OPTIMAL_EXT,
        DEPTH_READ_ONLY_STENCIL_ATTACHMENT_OPTIMAL_KHR,
        DEPTH_ATTACHMENT_STENCIL_READ_ONLY_OPTIMAL_KHR,
        SHADING_RATE_OPTIMAL_NV,
        DEPTH_ATTACHMENT_OPTIMAL_KHR,
        DEPTH_READ_ONLY_OPTIMAL_KHR,
        STENCIL_ATTACHMENT_OPTIMAL_KHR,
        STENCIL_READ_ONLY_OPTIMAL_KHR,
        READ_ONLY_OPTIMAL_KHR,
        ATTACHMENT_OPTIMAL_KHR,
        MAX_ENUM
    };

}
