/**
* @file AccessFlags.h
* @author Andrew Fagan
* @date 6/12/2025
*/

#pragma once

#include "Core/FixedIntegerTypes.h"

namespace Astral {

    enum class AccessFlags : uint8
    {
        INDIRECT_COMMAND_READ_BIT,
        INDEX_READ_BIT,
        VERTEX_ATTRIBUTE_READ_BIT,
        UNIFORM_READ_BIT,
        INPUT_ATTACHMENT_READ_BIT,
        SHADER_READ_BIT,
        SHADER_WRITE_BIT,
        COLOR_ATTACHMENT_READ_BIT,
        COLOR_ATTACHMENT_WRITE_BIT,
        DEPTH_STENCIL_ATTACHMENT_READ_BIT,
        DEPTH_STENCIL_ATTACHMENT_WRITE_BIT,
        TRANSFER_READ_BIT,
        TRANSFER_WRITE_BIT,
        HOST_READ_BIT,
        HOST_WRITE_BIT,
        MEMORY_READ_BIT,
        MEMORY_WRITE_BIT,
        NONE,
        TRANSFORM_FEEDBACK_WRITE_BIT_EXT,
        TRANSFORM_FEEDBACK_COUNTER_READ_BIT_EXT,
        TRANSFORM_FEEDBACK_COUNTER_WRITE_BIT_EXT,
        CONDITIONAL_RENDERING_READ_BIT_EXT,
        COLOR_ATTACHMENT_READ_NONCOHERENT_BIT_EXT,
        FRAGMENT_DENSITY_MAP_READ_BIT_EXT,
        COMMAND_PREPROCESS_READ_BIT_EXT,
        COMMAND_PREPROCESS_WRITE_BIT_EXT,
    };

}